#!/usr/bin/env python3

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def generateFibonacciList(first, second, limit):
    """This function generates the fibonacci numbers with a uppper limit"""
    limit=int(limit)
    if first+second>limit:
        return []
    #create list 
    list=[]
    #calculate next element
    list.append(first+second)
    #recursive concatenate list
    list+=generateFibonacciList(second, first+second, limit)
    return list

def sumEvenFibonacci(limit):
    """sum up all even fibonaci numbers"""
    #generate numbers
    numbers=generateFibonacciList(1,2,int(limit))
    #only take even
    numbers=numbers[2::3]
    #return sum of all even numbers
    return sum(numbers)

print(sumEvenFibonacci(4e6))
