#!/usr/bin/env python

"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""
from math import sqrt,floor
from numpy import round

def give_pentagonal(n):
    return n*(3*n-1)/2


def is_pentagonal(p):
   return (1+sqrt(1+24*p))/6%1==0


def solveProblem():
    min = 1e7
    for i in range(1,int(5e3)):
        for j in range(1,i+1):
            p1 = (give_pentagonal(i))
            p2 = (give_pentagonal(j))
            diff = p1-p2
            if is_pentagonal(diff) and is_pentagonal(p1+p2) and diff<min:
                min = diff
                print(p1)
    return min




print(solveProblem())

