#!/usr/bin/env python

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from eulerfunctions import is_hexagonal, is_pentagonal, is_triangle_number

def solveProblem():
    for i in range(1,int(1e8)):
        t = i*(i+1)/2
        if is_hexagonal(t) and is_pentagonal(t) and t>40755:
            return int(t)
    return 0

print(solveProblem())
