#!/usr/bin/env python

"""
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
"""


def triangle(n):
    return n*(n+1)//2

def square(n):
    return n**2

def pentagonal(n):
    return n*(3*n-1)//2

def hexagonal(n):
    return n*(2*n-1)

def heptagonal(n):
    return n*(5*n-3)//2

def octagonal(n):
    return n*(3*n-2)


def compare(a,b):
    return str(a)[2:] == str(b)[0:2]


def next_chain(ch, nums, hist):
    if len(ch) == 6:
        if compare(ch[-1], ch[0]):
            # print(ch)
            return True,ch
        else:
            return False,ch
    for (num,id) in nums:
        if id not in hist:
            if len(ch) == 0 or compare(ch[-1], num):
                hist.append(id)
                ch.append(num)
                nums.remove((num,id))
                res, ch_ = next_chain(ch, nums, hist) 
                if res == True:
                    return True,ch_
                else: 
                    ch.remove(num) 
                    hist.remove(id)
                    nums.append((num,id))
    return False,0         
    

def solve():
    
    tr = [(triangle(n),3) for n in range(500)]
    tr = list(filter(lambda x: x[0]>=1000 and x[0]<=10000, tr))
    
    sq = [(square(n),4) for n in range(500)]
    sq = list(filter(lambda x: x[0]>=1000 and x[0]<=10000, sq))
        
    pe = [(pentagonal(n),5) for n in range(500)]
    pe = list(filter(lambda x: x[0]>=1000 and x[0]<=10000, pe))

    hx = [(hexagonal(n),6) for n in range(500)]
    hx = list(filter(lambda x: x[0]>=1000 and x[0]<=10000, hx))
    
    he = [(heptagonal(n),7) for n in range(500)]
    he = list(filter(lambda x: x[0]>=1000 and x[0]<=10000, he))
    
    oc = [(octagonal(n),8) for n in range(500)]
    oc = list(filter(lambda x: x[0]>=1000 and x[0]<=10000, oc))

    #contains all numbers
    numbers = tr + sq + pe + hx + he + oc
    _, x = next_chain([], numbers, [])
    return sum(x)

print(solve())
